# Generated by Django 3.1 on 2021-08-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created', 'complete']},
        ),
    ]
