# Generated by Django 3.1 on 2021-08-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210803_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created', 'complete']},
        ),
    ]
