# Generated by Django 3.1 on 2021-08-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210803_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-created']},
        ),
    ]
